version: '3.9'

services:
  mongo:
    image: mongo
    container_name: your_id_devchallenge_21_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: your_id_devchallenge_21_api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=AudioInsightDb

volumes:
  mongo_data:
