version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo_audio_insight_devchallenge_21
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: api_audio_insight_devchallenge_21
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=AudioInsightDb

volumes:
  mongo_data:
